try{
    console.log(c+d)
}catch(err){
//Reference error bc varaible are not declared
console.log(err) 
console.log("There was an error");
console.log("The error was saved in a error log")
}
console.log("this line now runs")

